### PR TITLE
Fix return to previous checkout command

### LINKED ISSUE #39: `returnToPreviousCheckout` doesn't work
See [lib/commands/commit.js#L51-L55](https://github.com/poetic/ember-cli-github-pages/blob/master/lib/commands/commit.js#L51-L55)

The command to checkout previous branch doen't work

### PR DESCRIPTION
**Pull request by offirgolan**
Resolves #39

Im assuming the flow is

Lets say I start from `master`

1. checkout `gh-pages`
2. something something commit
3. checkout `master`
4. Push to origin

### CODE REVIEW

File: lib/commands/commit.js [hunk 1]
```diff
@@ -49,9 +49,7 @@ module.exports = {
     }
 
     function returnToPreviousCheckout() {
-      // Each '\' needed to be escaped here
-      return runCommand("git checkout `git reflog HEAD | sed -n " +
-        "'/checkout/ !d; s/.* \\(\\S*\\)$/\\1/;p' | sed '2 !d'`", execOptions);
+      return runCommand("git checkout -", execOptions);
```
Comment (offirgolan) [inline lib/commands/commit.js]: fixed :smile:

**Comment by osxi** [comment]
Looks good to me
